services:
  - type: web
    name: sme-script-platform
    env: node
    plan: free
    buildCommand: node build_demo.js
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_VERSION
        value: 20
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: sme-db
          property: internalConnectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: sme-db
    plan: free
